#
# /etc/pacman.conf - Configuration pacman pour nemOS (i686)
# Basé sur Arch Linux 32
#
# SPDX-License-Identifier: GPL-3.0-or-later

[options]
RootDir     = /
DBPath      = /var/lib/pacman/
CacheDir    = /var/cache/pacman/pkg/
LogFile     = /var/log/pacman.log
GPGDir      = /etc/pacman.d/gnupg/
HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
Architecture = i686

# Désactiver la vérification GPG pour les paquets i686 (compatibilité)
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
RemoteFileSigLevel = Optional

Color
ParallelDownloads = 3
CheckSpace
VerbosePkgLists

# Ne pas mettre à jour le noyau pendant le live
IgnorePkg   = linux

#
# DÉPÔTS ARCH LINUX 32
#
[core]
Include = /etc/pacman.d/mirrorlist32

[extra]
Include = /etc/pacman.d/mirrorlist32

[community]
Include = /etc/pacman.d/mirrorlist32

#
# DÉPÔTS nemOS (paquets personnalisés)
#
[nemos]
SigLevel = Optional TrustAll
Server = https://raw.githubusercontent.com/nemesisastarte-gif/nemOS/main/nemos-repo/$arch