---
# Calamares Configuration - nemOS
# Installer graphique pour nemOS 32-bit (i386)

# Recherche des modules : local uniquement (pas de recherche dans les chemins système)
modules-search: [local]

# Sequence d'installation - ordre des modules
instances:
  -
    - name: welcome
      id: welcome
    - name: locale
      id: locale
    - name: keyboard
      id: keyboard
    - name: partition
      id: partition
    - name: users
      id: users
    - name: network
      id: network
    - name: packages
      id: packages
    - name: services
      id: services
    - name: bootloader
      id: bootloader
    - name: shellprocess
      id: shellprocess
    - name: displaymanager
      id: displaymanager
    - name: finished
      id: finished

# Identité visuelle
branding: nemOS

# Taille de la fenêtre de l'installeur
window-size: 800x520
window-expands: false

# Chemins de stockage temporaire
# (laisser vide pour les valeurs par défaut)